name: Unit-tests

on:
- push
- pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6.x, 3.7.x, 3.8.x, 3.9.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.in
        pip install -e .
        ipython profile create
    - name: Run tests
      run: pytest -v -s
